###########
# site.title

title:    'Katherine M. Fitzpatrick'
subtitle: 'Programmer | Designer | Artist'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
